version: '3.2'

services:
  ocs:
    image: registry.der.rj:5000/ocsinventory
    environment:
      OCS_DBNAME: ${MYSQL_DATABASE}
      OCS_DBSERVER_READ: ${MYSQL_SERVER_HOST}
      OCS_DBSERVER_WRITE: ${MYSQL_SERVER_HOST}
      OCS_DBUSER: ${MYSQL_USER}
      OCS_DBPASS: ${MYSQL_PASSWORD}
    volumes:
      - ocsserver:/usr/share/ocsinventory-reports/
      - ocsserver:/etc/ocsinventory-reports/
      - ocsserver:/var/lib/ocsinventory-reports/
#   ports:
#      - target: 80
#        published: 80
#        protocol: tcp
#        mode: host
#    ports:
#      - 80:80
#      - 443:443
    networks:
      - proxy
      - default
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.serviceDomain=ocs.der.rj
        - com.df.port=8080
#      placement:
#        constraints: [node.role == worker]
#    container_name: ocsinventory-server

  db:
    image: registry.der.rj:5000/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - database:/var/lib/mysql
#    deploy:
#      placement:
#        constraints: [node.role == worker]
#    container_name: database

  glpi:
    image: registry.der.rj:5000/glpi
#    ports:
#      - target: 80
#        published: 8080
#        protocol: tcp
#        mode: host
#    ports:
#      - "80"
    volumes:
      - glpiserver:/var/www/glpi
    networks:
      - proxy
      - default
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.serviceDomain=glpi.der.rj
        - com.df.port=8080
#      placement:
#        constraints: [node.role == worker]
#    container_name: glpi-server

#volumes:
#  database:
#  ocsserver:
#  glpiserver:
volumes:
  ocsserver:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.144.242,nolock,soft,rw
      device: ":/opt/volumes/ocs"
  glpiserver:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.144.242,nolock,soft,rw
      device: ":/opt/volumes/glpi"
  database:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.144.242,nolock,soft,rw
      device: ":/opt/volumes/database"
      
networks:
  default:
    external: false
  proxy:
    external: true
